### ISSUE TITLE
Realtime Video

### ISSUE THREAD

**Issue by Zumbalamambo** [ildoonet/tf-openpose#1]
How do I make realtime prediction of landmarks?

**Comment by ildoonet** [comment]
@Zumbalamambo This is on-going implementation for openpose.

I will add realtime prediction within few weeks.

**Comment by felixfuu** [comment]
@ildoonet  can you share a inference demo for this work?

**Comment by ildoonet** [comment]
@Zumbalamambo 

See updated readme.

https://github.com/ildoonet/tf-openpose#realtime-webcam
