### ISSUE TITLE
tensorflow meta model can not import to mobile device 

### ISSUE THREAD

**Issue by Minotaur-CN** [ildoonet/tf-openpose#2]
Dear ildoonet,

Thanks for your excellent implementation. The model your provided is meta&index model , but the mobile tensorflow only could import .pb model.
Could provide the .pb model on the wget download?
Thanks very much !

Regards!

**Comment by ildoonet** [comment]
@Minotaur-CN 

Provided model is not trained well, So I'm trying to train a good performance model.

Wait for few weeks...

**Comment by Minotaur-CN** [comment]
Thanks!

**Comment by CheMcCandless** [comment]
Could you plz provide the graph.pb file of mobilenet based openpose?
