### ISSUE TITLE
predict point value is always (0,0)

### ISSUE THREAD

**Issue by pobei** [ildoonet/tf-openpose#20]
emm,I use tensorflow 1.2.1 and python2.7 and use the cmu model，however the result is all zero. 
 i print the humans var:
{0: (0, (0, 0), 0.76720679), 1: (1, (0, 0), 0.52168292), 2: (2, (0, 0), 0.35121292), 3: (3, (0, 0), 0.16420589), 4: (4, (0, 0), 0.72281742), 5: (5, (0, 0), 0.56922513), 6: (6, (0, 0), 0.11180361), 14: (14, (0, 0), 0.85471308), 15: (15, (0, 0), 0.90744114), 16: (16, (0, 0), 0.8026157), 17: (17, (0, 0), 0.74373686)})

**Comment by YuliangXiu** [comment]
In python2 environment, it's necessary to edit connection_to_human function as follows:

> def connections_to_human(connections, heatMat):
    point_dict = defaultdict(lambda: None)
    for conn in connections:
        point_dict[conn['partIdx'][0]] = (conn['partIdx'][0], (conn['c1'][0]*1.0 / heatMat.shape[2], conn['c1'][1]*1.0 / heatMat.shape[1]), heatMat[conn['partIdx'][0], conn['c1'][1], conn['c1'][0]])
        point_dict[conn['partIdx'][1]] = (conn['partIdx'][1], (conn['c2'][0]*1.0 / heatMat.shape[2], conn['c2'][1]*1.0 / heatMat.shape[1]), heatMat[conn['partIdx'][1], conn['c2'][1], conn['c2'][0]])
    return point_dict

**Comment by oguzhankarabulut** [comment]
How should it be in python3? I want to print joint coordinates too
