### ISSUE TITLE
Help for annotation on the source code!

### ISSUE THREAD

**Issue by StrongerSuperman** [ildoonet/tf-openpose#8]
Since you release the repo of openpose of tf version, I've been watching your progress and reading the src which is rather standard in code format, But I got some problem when reading the code cuz I am a beginner of Deep learning, I'm wondering could you add some annotation on the source code? such as the pose_dataset.py file, for I just wanna use your code to trian the model which is based on my own dataset instead of Cocodataset but I don't know how to format the LMDB file from my own dataset to match your trian code, thanks!

**Comment by ildoonet** [comment]
i will. I have to change and implement more. After this, I will clean codes and add more explanations.
